apiVersion: v1
kind: Secret
metadata:
  name: rayanah-docker-hub-creds
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/ # Described below
type: kubernetes.io/basic-auth
stringData:
  username: rayanah
  password: 7d3e201f-76ce-42e8-bf3f-8fd450cf9c69
